print("Hello, my name is Angel.")
print("I like playing sports with my friends and other people.")
print("Singing is one of my greatest passions in life.")
print("Lionel Messi is the best player in soccer history.")
print("When Ed Sheeran said \"Be a true heart, not a follower\", bro, I really felt that.")